/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUsageTypesIndexRouteImport } from './routes/_authenticated/usage-types/index'
import { Route as AuthenticatedUpgradePackagesIndexRouteImport } from './routes/_authenticated/upgrade-packages/index'
import { Route as AuthenticatedTechSupportIndexRouteImport } from './routes/_authenticated/tech-support/index'
import { Route as AuthenticatedStatusesIndexRouteImport } from './routes/_authenticated/statuses/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicePackagesIndexRouteImport } from './routes/_authenticated/service-packages/index'
import { Route as AuthenticatedServiceCallsIndexRouteImport } from './routes/_authenticated/service-calls/index'
import { Route as AuthenticatedRepositoryIndexRouteImport } from './routes/_authenticated/repository/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProtectivesIndexRouteImport } from './routes/_authenticated/protectives/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPriceListIndexRouteImport } from './routes/_authenticated/price-list/index'
import { Route as AuthenticatedOwnersIndexRouteImport } from './routes/_authenticated/owners/index'
import { Route as AuthenticatedOpinionsIndexRouteImport } from './routes/_authenticated/opinions/index'
import { Route as AuthenticatedMileageAdjustmentsIndexRouteImport } from './routes/_authenticated/mileage-adjustments/index'
import { Route as AuthenticatedMarksIndexRouteImport } from './routes/_authenticated/marks/index'
import { Route as AuthenticatedManufacturersIndexRouteImport } from './routes/_authenticated/manufacturers/index'
import { Route as AuthenticatedIntegralExtrasIndexRouteImport } from './routes/_authenticated/integral-extras/index'
import { Route as AuthenticatedImportersIndexRouteImport } from './routes/_authenticated/importers/index'
import { Route as AuthenticatedGearboxesIndexRouteImport } from './routes/_authenticated/gearboxes/index'
import { Route as AuthenticatedExtrasIndexRouteImport } from './routes/_authenticated/extras/index'
import { Route as AuthenticatedEngineTypesIndexRouteImport } from './routes/_authenticated/engine-types/index'
import { Route as AuthenticatedDriveTypesIndexRouteImport } from './routes/_authenticated/drive-types/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCountriesIndexRouteImport } from './routes/_authenticated/countries/index'
import { Route as AuthenticatedCommentsForOpinionIndexRouteImport } from './routes/_authenticated/comments-for-opinion/index'
import { Route as AuthenticatedCodesIndexRouteImport } from './routes/_authenticated/codes/index'
import { Route as AuthenticatedClientSupportIndexRouteImport } from './routes/_authenticated/client-support/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog/index'
import { Route as AuthenticatedCarTypesIndexRouteImport } from './routes/_authenticated/car-types/index'
import { Route as AuthenticatedBodyTypesIndexRouteImport } from './routes/_authenticated/body-types/index'
import { Route as AuthenticatedAppraisersIndexRouteImport } from './routes/_authenticated/appraisers/index'
import { Route as AuthenticatedAdvertisementsIndexRouteImport } from './routes/_authenticated/advertisements/index'
import { Route as AuthenticatedAccessoriesIndexRouteImport } from './routes/_authenticated/accessories/index'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users/new'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users/$id'
import { Route as AuthenticatedTechSupportNewRouteImport } from './routes/_authenticated/tech-support/new'
import { Route as AuthenticatedTechSupportIdRouteImport } from './routes/_authenticated/tech-support/$id'
import { Route as AuthenticatedPriceListAdvertisementsRouteImport } from './routes/_authenticated/price-list/advertisements'
import { Route as AuthenticatedOpinionsNewRouteImport } from './routes/_authenticated/opinions/new'
import { Route as AuthenticatedOpinionsIdRouteImport } from './routes/_authenticated/opinions/$id'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers/new'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers/$id'
import { Route as AuthenticatedCodesSyncRouteImport } from './routes/_authenticated/codes/sync'
import { Route as AuthenticatedCodesNewRouteImport } from './routes/_authenticated/codes/new'
import { Route as AuthenticatedCodesIdRouteImport } from './routes/_authenticated/codes/$id'
import { Route as AuthenticatedClientSupportIdRouteImport } from './routes/_authenticated/client-support/$id'
import { Route as AuthenticatedCatalogPricesRouteImport } from './routes/_authenticated/catalog/prices'
import { Route as AuthenticatedCatalogNewCarRouteImport } from './routes/_authenticated/catalog/new-car'
import { Route as AuthenticatedCatalogIdRouteImport } from './routes/_authenticated/catalog/$id'
import { Route as AuthenticatedReportsSubscriptionIndexRouteImport } from './routes/_authenticated/reports/subscription/index'
import { Route as AuthenticatedReportsStatisticsIndexRouteImport } from './routes/_authenticated/reports/statistics/index'
import { Route as AuthenticatedReportsSearchQueriesIndexRouteImport } from './routes/_authenticated/reports/search-queries/index'
import { Route as AuthenticatedReportsPriceDifferencesIndexRouteImport } from './routes/_authenticated/reports/price-differences/index'
import { Route as AuthenticatedReportsNewModelsIndexRouteImport } from './routes/_authenticated/reports/new-models/index'
import { Route as AuthenticatedReportsLowYearExceedsHighIndexRouteImport } from './routes/_authenticated/reports/low-year-exceeds-high/index'
import { Route as AuthenticatedReportsLeadingQueriesIndexRouteImport } from './routes/_authenticated/reports/leading-queries/index'
import { Route as AuthenticatedReportsDeductedModelsIndexRouteImport } from './routes/_authenticated/reports/deducted-models/index'
import { Route as AuthenticatedReportsCatalogItemsIndexRouteImport } from './routes/_authenticated/reports/catalog-items/index'
import { Route as AuthenticatedReportsCarByYearsIndexRouteImport } from './routes/_authenticated/reports/car-by-years/index'
import { Route as AuthenticatedPriceListAdvertisementsIndexRouteImport } from './routes/_authenticated/price-list/advertisements/index'
import { Route as AuthenticatedCatalogEditIndexRouteImport } from './routes/_authenticated/catalog/edit/index'
import { Route as AuthenticatedManufacturersEditIdRouteImport } from './routes/_authenticated/manufacturers/edit/$id'
import { Route as AuthenticatedCatalogEditIdRouteImport } from './routes/_authenticated/catalog/edit/$id'
import { Route as AuthenticatedPriceListAdvertisementsTestIndexRouteImport } from './routes/_authenticated/price-list/advertisements/test/index'
import { Route as AuthenticatedPriceListAdvertisementsLayoutsIndexRouteImport } from './routes/_authenticated/price-list/advertisements/layouts/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageTypesIndexRoute =
  AuthenticatedUsageTypesIndexRouteImport.update({
    id: '/usage-types/',
    path: '/usage-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUpgradePackagesIndexRoute =
  AuthenticatedUpgradePackagesIndexRouteImport.update({
    id: '/upgrade-packages/',
    path: '/upgrade-packages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTechSupportIndexRoute =
  AuthenticatedTechSupportIndexRouteImport.update({
    id: '/tech-support/',
    path: '/tech-support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStatusesIndexRoute =
  AuthenticatedStatusesIndexRouteImport.update({
    id: '/statuses/',
    path: '/statuses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicePackagesIndexRoute =
  AuthenticatedServicePackagesIndexRouteImport.update({
    id: '/service-packages/',
    path: '/service-packages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServiceCallsIndexRoute =
  AuthenticatedServiceCallsIndexRouteImport.update({
    id: '/service-calls/',
    path: '/service-calls/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoryIndexRoute =
  AuthenticatedRepositoryIndexRouteImport.update({
    id: '/repository/',
    path: '/repository/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedProtectivesIndexRoute =
  AuthenticatedProtectivesIndexRouteImport.update({
    id: '/protectives/',
    path: '/protectives/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPriceListIndexRoute =
  AuthenticatedPriceListIndexRouteImport.update({
    id: '/price-list/',
    path: '/price-list/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnersIndexRoute =
  AuthenticatedOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpinionsIndexRoute =
  AuthenticatedOpinionsIndexRouteImport.update({
    id: '/opinions/',
    path: '/opinions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMileageAdjustmentsIndexRoute =
  AuthenticatedMileageAdjustmentsIndexRouteImport.update({
    id: '/mileage-adjustments/',
    path: '/mileage-adjustments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarksIndexRoute = AuthenticatedMarksIndexRouteImport.update({
  id: '/marks/',
  path: '/marks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManufacturersIndexRoute =
  AuthenticatedManufacturersIndexRouteImport.update({
    id: '/manufacturers/',
    path: '/manufacturers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegralExtrasIndexRoute =
  AuthenticatedIntegralExtrasIndexRouteImport.update({
    id: '/integral-extras/',
    path: '/integral-extras/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportersIndexRoute =
  AuthenticatedImportersIndexRouteImport.update({
    id: '/importers/',
    path: '/importers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGearboxesIndexRoute =
  AuthenticatedGearboxesIndexRouteImport.update({
    id: '/gearboxes/',
    path: '/gearboxes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtrasIndexRoute =
  AuthenticatedExtrasIndexRouteImport.update({
    id: '/extras/',
    path: '/extras/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEngineTypesIndexRoute =
  AuthenticatedEngineTypesIndexRouteImport.update({
    id: '/engine-types/',
    path: '/engine-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDriveTypesIndexRoute =
  AuthenticatedDriveTypesIndexRouteImport.update({
    id: '/drive-types/',
    path: '/drive-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesIndexRoute =
  AuthenticatedCountriesIndexRouteImport.update({
    id: '/countries/',
    path: '/countries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommentsForOpinionIndexRoute =
  AuthenticatedCommentsForOpinionIndexRouteImport.update({
    id: '/comments-for-opinion/',
    path: '/comments-for-opinion/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCodesIndexRoute = AuthenticatedCodesIndexRouteImport.update({
  id: '/codes/',
  path: '/codes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientSupportIndexRoute =
  AuthenticatedClientSupportIndexRouteImport.update({
    id: '/client-support/',
    path: '/client-support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarTypesIndexRoute =
  AuthenticatedCarTypesIndexRouteImport.update({
    id: '/car-types/',
    path: '/car-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBodyTypesIndexRoute =
  AuthenticatedBodyTypesIndexRouteImport.update({
    id: '/body-types/',
    path: '/body-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppraisersIndexRoute =
  AuthenticatedAppraisersIndexRouteImport.update({
    id: '/appraisers/',
    path: '/appraisers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdvertisementsIndexRoute =
  AuthenticatedAdvertisementsIndexRouteImport.update({
    id: '/advertisements/',
    path: '/advertisements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccessoriesIndexRoute =
  AuthenticatedAccessoriesIndexRouteImport.update({
    id: '/accessories/',
    path: '/accessories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTechSupportNewRoute =
  AuthenticatedTechSupportNewRouteImport.update({
    id: '/tech-support/new',
    path: '/tech-support/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTechSupportIdRoute =
  AuthenticatedTechSupportIdRouteImport.update({
    id: '/tech-support/$id',
    path: '/tech-support/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPriceListAdvertisementsRoute =
  AuthenticatedPriceListAdvertisementsRouteImport.update({
    id: '/price-list/advertisements',
    path: '/price-list/advertisements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpinionsNewRoute =
  AuthenticatedOpinionsNewRouteImport.update({
    id: '/opinions/new',
    path: '/opinions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpinionsIdRoute = AuthenticatedOpinionsIdRouteImport.update({
  id: '/opinions/$id',
  path: '/opinions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCodesSyncRoute = AuthenticatedCodesSyncRouteImport.update({
  id: '/codes/sync',
  path: '/codes/sync',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodesNewRoute = AuthenticatedCodesNewRouteImport.update({
  id: '/codes/new',
  path: '/codes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCodesIdRoute = AuthenticatedCodesIdRouteImport.update({
  id: '/codes/$id',
  path: '/codes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientSupportIdRoute =
  AuthenticatedClientSupportIdRouteImport.update({
    id: '/client-support/$id',
    path: '/client-support/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogPricesRoute =
  AuthenticatedCatalogPricesRouteImport.update({
    id: '/catalog/prices',
    path: '/catalog/prices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogNewCarRoute =
  AuthenticatedCatalogNewCarRouteImport.update({
    id: '/catalog/new-car',
    path: '/catalog/new-car',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogIdRoute = AuthenticatedCatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsSubscriptionIndexRoute =
  AuthenticatedReportsSubscriptionIndexRouteImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsStatisticsIndexRoute =
  AuthenticatedReportsStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsSearchQueriesIndexRoute =
  AuthenticatedReportsSearchQueriesIndexRouteImport.update({
    id: '/search-queries/',
    path: '/search-queries/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsPriceDifferencesIndexRoute =
  AuthenticatedReportsPriceDifferencesIndexRouteImport.update({
    id: '/price-differences/',
    path: '/price-differences/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsNewModelsIndexRoute =
  AuthenticatedReportsNewModelsIndexRouteImport.update({
    id: '/new-models/',
    path: '/new-models/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsLowYearExceedsHighIndexRoute =
  AuthenticatedReportsLowYearExceedsHighIndexRouteImport.update({
    id: '/low-year-exceeds-high/',
    path: '/low-year-exceeds-high/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsLeadingQueriesIndexRoute =
  AuthenticatedReportsLeadingQueriesIndexRouteImport.update({
    id: '/leading-queries/',
    path: '/leading-queries/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsDeductedModelsIndexRoute =
  AuthenticatedReportsDeductedModelsIndexRouteImport.update({
    id: '/deducted-models/',
    path: '/deducted-models/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsCatalogItemsIndexRoute =
  AuthenticatedReportsCatalogItemsIndexRouteImport.update({
    id: '/catalog-items/',
    path: '/catalog-items/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedReportsCarByYearsIndexRoute =
  AuthenticatedReportsCarByYearsIndexRouteImport.update({
    id: '/car-by-years/',
    path: '/car-by-years/',
    getParentRoute: () => AuthenticatedReportsRoute,
  } as any)
const AuthenticatedPriceListAdvertisementsIndexRoute =
  AuthenticatedPriceListAdvertisementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPriceListAdvertisementsRoute,
  } as any)
const AuthenticatedCatalogEditIndexRoute =
  AuthenticatedCatalogEditIndexRouteImport.update({
    id: '/catalog/edit/',
    path: '/catalog/edit/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManufacturersEditIdRoute =
  AuthenticatedManufacturersEditIdRouteImport.update({
    id: '/manufacturers/edit/$id',
    path: '/manufacturers/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogEditIdRoute =
  AuthenticatedCatalogEditIdRouteImport.update({
    id: '/catalog/edit/$id',
    path: '/catalog/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPriceListAdvertisementsTestIndexRoute =
  AuthenticatedPriceListAdvertisementsTestIndexRouteImport.update({
    id: '/test/',
    path: '/test/',
    getParentRoute: () => AuthenticatedPriceListAdvertisementsRoute,
  } as any)
const AuthenticatedPriceListAdvertisementsLayoutsIndexRoute =
  AuthenticatedPriceListAdvertisementsLayoutsIndexRouteImport.update({
    id: '/layouts/',
    path: '/layouts/',
    getParentRoute: () => AuthenticatedPriceListAdvertisementsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/reports': typeof AuthenticatedReportsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/catalog/$id': typeof AuthenticatedCatalogIdRoute
  '/catalog/new-car': typeof AuthenticatedCatalogNewCarRoute
  '/catalog/prices': typeof AuthenticatedCatalogPricesRoute
  '/client-support/$id': typeof AuthenticatedClientSupportIdRoute
  '/codes/$id': typeof AuthenticatedCodesIdRoute
  '/codes/new': typeof AuthenticatedCodesNewRoute
  '/codes/sync': typeof AuthenticatedCodesSyncRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/opinions/$id': typeof AuthenticatedOpinionsIdRoute
  '/opinions/new': typeof AuthenticatedOpinionsNewRoute
  '/price-list/advertisements': typeof AuthenticatedPriceListAdvertisementsRouteWithChildren
  '/tech-support/$id': typeof AuthenticatedTechSupportIdRoute
  '/tech-support/new': typeof AuthenticatedTechSupportNewRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/accessories': typeof AuthenticatedAccessoriesIndexRoute
  '/advertisements': typeof AuthenticatedAdvertisementsIndexRoute
  '/appraisers': typeof AuthenticatedAppraisersIndexRoute
  '/body-types': typeof AuthenticatedBodyTypesIndexRoute
  '/car-types': typeof AuthenticatedCarTypesIndexRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/client-support': typeof AuthenticatedClientSupportIndexRoute
  '/codes': typeof AuthenticatedCodesIndexRoute
  '/comments-for-opinion': typeof AuthenticatedCommentsForOpinionIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drive-types': typeof AuthenticatedDriveTypesIndexRoute
  '/engine-types': typeof AuthenticatedEngineTypesIndexRoute
  '/extras': typeof AuthenticatedExtrasIndexRoute
  '/gearboxes': typeof AuthenticatedGearboxesIndexRoute
  '/importers': typeof AuthenticatedImportersIndexRoute
  '/integral-extras': typeof AuthenticatedIntegralExtrasIndexRoute
  '/manufacturers': typeof AuthenticatedManufacturersIndexRoute
  '/marks': typeof AuthenticatedMarksIndexRoute
  '/mileage-adjustments': typeof AuthenticatedMileageAdjustmentsIndexRoute
  '/opinions': typeof AuthenticatedOpinionsIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/price-list': typeof AuthenticatedPriceListIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/protectives': typeof AuthenticatedProtectivesIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/repository': typeof AuthenticatedRepositoryIndexRoute
  '/service-calls': typeof AuthenticatedServiceCallsIndexRoute
  '/service-packages': typeof AuthenticatedServicePackagesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/statuses': typeof AuthenticatedStatusesIndexRoute
  '/tech-support': typeof AuthenticatedTechSupportIndexRoute
  '/upgrade-packages': typeof AuthenticatedUpgradePackagesIndexRoute
  '/usage-types': typeof AuthenticatedUsageTypesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/catalog/edit/$id': typeof AuthenticatedCatalogEditIdRoute
  '/manufacturers/edit/$id': typeof AuthenticatedManufacturersEditIdRoute
  '/catalog/edit': typeof AuthenticatedCatalogEditIndexRoute
  '/price-list/advertisements/': typeof AuthenticatedPriceListAdvertisementsIndexRoute
  '/reports/car-by-years': typeof AuthenticatedReportsCarByYearsIndexRoute
  '/reports/catalog-items': typeof AuthenticatedReportsCatalogItemsIndexRoute
  '/reports/deducted-models': typeof AuthenticatedReportsDeductedModelsIndexRoute
  '/reports/leading-queries': typeof AuthenticatedReportsLeadingQueriesIndexRoute
  '/reports/low-year-exceeds-high': typeof AuthenticatedReportsLowYearExceedsHighIndexRoute
  '/reports/new-models': typeof AuthenticatedReportsNewModelsIndexRoute
  '/reports/price-differences': typeof AuthenticatedReportsPriceDifferencesIndexRoute
  '/reports/search-queries': typeof AuthenticatedReportsSearchQueriesIndexRoute
  '/reports/statistics': typeof AuthenticatedReportsStatisticsIndexRoute
  '/reports/subscription': typeof AuthenticatedReportsSubscriptionIndexRoute
  '/price-list/advertisements/layouts': typeof AuthenticatedPriceListAdvertisementsLayoutsIndexRoute
  '/price-list/advertisements/test': typeof AuthenticatedPriceListAdvertisementsTestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/catalog/$id': typeof AuthenticatedCatalogIdRoute
  '/catalog/new-car': typeof AuthenticatedCatalogNewCarRoute
  '/catalog/prices': typeof AuthenticatedCatalogPricesRoute
  '/client-support/$id': typeof AuthenticatedClientSupportIdRoute
  '/codes/$id': typeof AuthenticatedCodesIdRoute
  '/codes/new': typeof AuthenticatedCodesNewRoute
  '/codes/sync': typeof AuthenticatedCodesSyncRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/opinions/$id': typeof AuthenticatedOpinionsIdRoute
  '/opinions/new': typeof AuthenticatedOpinionsNewRoute
  '/tech-support/$id': typeof AuthenticatedTechSupportIdRoute
  '/tech-support/new': typeof AuthenticatedTechSupportNewRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/accessories': typeof AuthenticatedAccessoriesIndexRoute
  '/advertisements': typeof AuthenticatedAdvertisementsIndexRoute
  '/appraisers': typeof AuthenticatedAppraisersIndexRoute
  '/body-types': typeof AuthenticatedBodyTypesIndexRoute
  '/car-types': typeof AuthenticatedCarTypesIndexRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/client-support': typeof AuthenticatedClientSupportIndexRoute
  '/codes': typeof AuthenticatedCodesIndexRoute
  '/comments-for-opinion': typeof AuthenticatedCommentsForOpinionIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drive-types': typeof AuthenticatedDriveTypesIndexRoute
  '/engine-types': typeof AuthenticatedEngineTypesIndexRoute
  '/extras': typeof AuthenticatedExtrasIndexRoute
  '/gearboxes': typeof AuthenticatedGearboxesIndexRoute
  '/importers': typeof AuthenticatedImportersIndexRoute
  '/integral-extras': typeof AuthenticatedIntegralExtrasIndexRoute
  '/manufacturers': typeof AuthenticatedManufacturersIndexRoute
  '/marks': typeof AuthenticatedMarksIndexRoute
  '/mileage-adjustments': typeof AuthenticatedMileageAdjustmentsIndexRoute
  '/opinions': typeof AuthenticatedOpinionsIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/price-list': typeof AuthenticatedPriceListIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/protectives': typeof AuthenticatedProtectivesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/repository': typeof AuthenticatedRepositoryIndexRoute
  '/service-calls': typeof AuthenticatedServiceCallsIndexRoute
  '/service-packages': typeof AuthenticatedServicePackagesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/statuses': typeof AuthenticatedStatusesIndexRoute
  '/tech-support': typeof AuthenticatedTechSupportIndexRoute
  '/upgrade-packages': typeof AuthenticatedUpgradePackagesIndexRoute
  '/usage-types': typeof AuthenticatedUsageTypesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/catalog/edit/$id': typeof AuthenticatedCatalogEditIdRoute
  '/manufacturers/edit/$id': typeof AuthenticatedManufacturersEditIdRoute
  '/catalog/edit': typeof AuthenticatedCatalogEditIndexRoute
  '/price-list/advertisements': typeof AuthenticatedPriceListAdvertisementsIndexRoute
  '/reports/car-by-years': typeof AuthenticatedReportsCarByYearsIndexRoute
  '/reports/catalog-items': typeof AuthenticatedReportsCatalogItemsIndexRoute
  '/reports/deducted-models': typeof AuthenticatedReportsDeductedModelsIndexRoute
  '/reports/leading-queries': typeof AuthenticatedReportsLeadingQueriesIndexRoute
  '/reports/low-year-exceeds-high': typeof AuthenticatedReportsLowYearExceedsHighIndexRoute
  '/reports/new-models': typeof AuthenticatedReportsNewModelsIndexRoute
  '/reports/price-differences': typeof AuthenticatedReportsPriceDifferencesIndexRoute
  '/reports/search-queries': typeof AuthenticatedReportsSearchQueriesIndexRoute
  '/reports/statistics': typeof AuthenticatedReportsStatisticsIndexRoute
  '/reports/subscription': typeof AuthenticatedReportsSubscriptionIndexRoute
  '/price-list/advertisements/layouts': typeof AuthenticatedPriceListAdvertisementsLayoutsIndexRoute
  '/price-list/advertisements/test': typeof AuthenticatedPriceListAdvertisementsTestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/catalog/$id': typeof AuthenticatedCatalogIdRoute
  '/_authenticated/catalog/new-car': typeof AuthenticatedCatalogNewCarRoute
  '/_authenticated/catalog/prices': typeof AuthenticatedCatalogPricesRoute
  '/_authenticated/client-support/$id': typeof AuthenticatedClientSupportIdRoute
  '/_authenticated/codes/$id': typeof AuthenticatedCodesIdRoute
  '/_authenticated/codes/new': typeof AuthenticatedCodesNewRoute
  '/_authenticated/codes/sync': typeof AuthenticatedCodesSyncRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/opinions/$id': typeof AuthenticatedOpinionsIdRoute
  '/_authenticated/opinions/new': typeof AuthenticatedOpinionsNewRoute
  '/_authenticated/price-list/advertisements': typeof AuthenticatedPriceListAdvertisementsRouteWithChildren
  '/_authenticated/tech-support/$id': typeof AuthenticatedTechSupportIdRoute
  '/_authenticated/tech-support/new': typeof AuthenticatedTechSupportNewRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/accessories/': typeof AuthenticatedAccessoriesIndexRoute
  '/_authenticated/advertisements/': typeof AuthenticatedAdvertisementsIndexRoute
  '/_authenticated/appraisers/': typeof AuthenticatedAppraisersIndexRoute
  '/_authenticated/body-types/': typeof AuthenticatedBodyTypesIndexRoute
  '/_authenticated/car-types/': typeof AuthenticatedCarTypesIndexRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/client-support/': typeof AuthenticatedClientSupportIndexRoute
  '/_authenticated/codes/': typeof AuthenticatedCodesIndexRoute
  '/_authenticated/comments-for-opinion/': typeof AuthenticatedCommentsForOpinionIndexRoute
  '/_authenticated/countries/': typeof AuthenticatedCountriesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/drive-types/': typeof AuthenticatedDriveTypesIndexRoute
  '/_authenticated/engine-types/': typeof AuthenticatedEngineTypesIndexRoute
  '/_authenticated/extras/': typeof AuthenticatedExtrasIndexRoute
  '/_authenticated/gearboxes/': typeof AuthenticatedGearboxesIndexRoute
  '/_authenticated/importers/': typeof AuthenticatedImportersIndexRoute
  '/_authenticated/integral-extras/': typeof AuthenticatedIntegralExtrasIndexRoute
  '/_authenticated/manufacturers/': typeof AuthenticatedManufacturersIndexRoute
  '/_authenticated/marks/': typeof AuthenticatedMarksIndexRoute
  '/_authenticated/mileage-adjustments/': typeof AuthenticatedMileageAdjustmentsIndexRoute
  '/_authenticated/opinions/': typeof AuthenticatedOpinionsIndexRoute
  '/_authenticated/owners/': typeof AuthenticatedOwnersIndexRoute
  '/_authenticated/price-list/': typeof AuthenticatedPriceListIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/protectives/': typeof AuthenticatedProtectivesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/repository/': typeof AuthenticatedRepositoryIndexRoute
  '/_authenticated/service-calls/': typeof AuthenticatedServiceCallsIndexRoute
  '/_authenticated/service-packages/': typeof AuthenticatedServicePackagesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/statuses/': typeof AuthenticatedStatusesIndexRoute
  '/_authenticated/tech-support/': typeof AuthenticatedTechSupportIndexRoute
  '/_authenticated/upgrade-packages/': typeof AuthenticatedUpgradePackagesIndexRoute
  '/_authenticated/usage-types/': typeof AuthenticatedUsageTypesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_authenticated/catalog/edit/$id': typeof AuthenticatedCatalogEditIdRoute
  '/_authenticated/manufacturers/edit/$id': typeof AuthenticatedManufacturersEditIdRoute
  '/_authenticated/catalog/edit/': typeof AuthenticatedCatalogEditIndexRoute
  '/_authenticated/price-list/advertisements/': typeof AuthenticatedPriceListAdvertisementsIndexRoute
  '/_authenticated/reports/car-by-years/': typeof AuthenticatedReportsCarByYearsIndexRoute
  '/_authenticated/reports/catalog-items/': typeof AuthenticatedReportsCatalogItemsIndexRoute
  '/_authenticated/reports/deducted-models/': typeof AuthenticatedReportsDeductedModelsIndexRoute
  '/_authenticated/reports/leading-queries/': typeof AuthenticatedReportsLeadingQueriesIndexRoute
  '/_authenticated/reports/low-year-exceeds-high/': typeof AuthenticatedReportsLowYearExceedsHighIndexRoute
  '/_authenticated/reports/new-models/': typeof AuthenticatedReportsNewModelsIndexRoute
  '/_authenticated/reports/price-differences/': typeof AuthenticatedReportsPriceDifferencesIndexRoute
  '/_authenticated/reports/search-queries/': typeof AuthenticatedReportsSearchQueriesIndexRoute
  '/_authenticated/reports/statistics/': typeof AuthenticatedReportsStatisticsIndexRoute
  '/_authenticated/reports/subscription/': typeof AuthenticatedReportsSubscriptionIndexRoute
  '/_authenticated/price-list/advertisements/layouts/': typeof AuthenticatedPriceListAdvertisementsLayoutsIndexRoute
  '/_authenticated/price-list/advertisements/test/': typeof AuthenticatedPriceListAdvertisementsTestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/reports'
    | '/'
    | '/catalog/$id'
    | '/catalog/new-car'
    | '/catalog/prices'
    | '/client-support/$id'
    | '/codes/$id'
    | '/codes/new'
    | '/codes/sync'
    | '/customers/$id'
    | '/customers/new'
    | '/opinions/$id'
    | '/opinions/new'
    | '/price-list/advertisements'
    | '/tech-support/$id'
    | '/tech-support/new'
    | '/users/$id'
    | '/users/new'
    | '/accessories'
    | '/advertisements'
    | '/appraisers'
    | '/body-types'
    | '/car-types'
    | '/catalog'
    | '/categories'
    | '/client-support'
    | '/codes'
    | '/comments-for-opinion'
    | '/countries'
    | '/customers'
    | '/drive-types'
    | '/engine-types'
    | '/extras'
    | '/gearboxes'
    | '/importers'
    | '/integral-extras'
    | '/manufacturers'
    | '/marks'
    | '/mileage-adjustments'
    | '/opinions'
    | '/owners'
    | '/price-list'
    | '/profile'
    | '/protectives'
    | '/reports/'
    | '/repository'
    | '/service-calls'
    | '/service-packages'
    | '/settings'
    | '/statuses'
    | '/tech-support'
    | '/upgrade-packages'
    | '/usage-types'
    | '/users'
    | '/login'
    | '/catalog/edit/$id'
    | '/manufacturers/edit/$id'
    | '/catalog/edit'
    | '/price-list/advertisements/'
    | '/reports/car-by-years'
    | '/reports/catalog-items'
    | '/reports/deducted-models'
    | '/reports/leading-queries'
    | '/reports/low-year-exceeds-high'
    | '/reports/new-models'
    | '/reports/price-differences'
    | '/reports/search-queries'
    | '/reports/statistics'
    | '/reports/subscription'
    | '/price-list/advertisements/layouts'
    | '/price-list/advertisements/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog/$id'
    | '/catalog/new-car'
    | '/catalog/prices'
    | '/client-support/$id'
    | '/codes/$id'
    | '/codes/new'
    | '/codes/sync'
    | '/customers/$id'
    | '/customers/new'
    | '/opinions/$id'
    | '/opinions/new'
    | '/tech-support/$id'
    | '/tech-support/new'
    | '/users/$id'
    | '/users/new'
    | '/accessories'
    | '/advertisements'
    | '/appraisers'
    | '/body-types'
    | '/car-types'
    | '/catalog'
    | '/categories'
    | '/client-support'
    | '/codes'
    | '/comments-for-opinion'
    | '/countries'
    | '/customers'
    | '/drive-types'
    | '/engine-types'
    | '/extras'
    | '/gearboxes'
    | '/importers'
    | '/integral-extras'
    | '/manufacturers'
    | '/marks'
    | '/mileage-adjustments'
    | '/opinions'
    | '/owners'
    | '/price-list'
    | '/profile'
    | '/protectives'
    | '/reports'
    | '/repository'
    | '/service-calls'
    | '/service-packages'
    | '/settings'
    | '/statuses'
    | '/tech-support'
    | '/upgrade-packages'
    | '/usage-types'
    | '/users'
    | '/login'
    | '/catalog/edit/$id'
    | '/manufacturers/edit/$id'
    | '/catalog/edit'
    | '/price-list/advertisements'
    | '/reports/car-by-years'
    | '/reports/catalog-items'
    | '/reports/deducted-models'
    | '/reports/leading-queries'
    | '/reports/low-year-exceeds-high'
    | '/reports/new-models'
    | '/reports/price-differences'
    | '/reports/search-queries'
    | '/reports/statistics'
    | '/reports/subscription'
    | '/price-list/advertisements/layouts'
    | '/price-list/advertisements/test'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/reports'
    | '/_authenticated/'
    | '/_authenticated/catalog/$id'
    | '/_authenticated/catalog/new-car'
    | '/_authenticated/catalog/prices'
    | '/_authenticated/client-support/$id'
    | '/_authenticated/codes/$id'
    | '/_authenticated/codes/new'
    | '/_authenticated/codes/sync'
    | '/_authenticated/customers/$id'
    | '/_authenticated/customers/new'
    | '/_authenticated/opinions/$id'
    | '/_authenticated/opinions/new'
    | '/_authenticated/price-list/advertisements'
    | '/_authenticated/tech-support/$id'
    | '/_authenticated/tech-support/new'
    | '/_authenticated/users/$id'
    | '/_authenticated/users/new'
    | '/_authenticated/accessories/'
    | '/_authenticated/advertisements/'
    | '/_authenticated/appraisers/'
    | '/_authenticated/body-types/'
    | '/_authenticated/car-types/'
    | '/_authenticated/catalog/'
    | '/_authenticated/categories/'
    | '/_authenticated/client-support/'
    | '/_authenticated/codes/'
    | '/_authenticated/comments-for-opinion/'
    | '/_authenticated/countries/'
    | '/_authenticated/customers/'
    | '/_authenticated/drive-types/'
    | '/_authenticated/engine-types/'
    | '/_authenticated/extras/'
    | '/_authenticated/gearboxes/'
    | '/_authenticated/importers/'
    | '/_authenticated/integral-extras/'
    | '/_authenticated/manufacturers/'
    | '/_authenticated/marks/'
    | '/_authenticated/mileage-adjustments/'
    | '/_authenticated/opinions/'
    | '/_authenticated/owners/'
    | '/_authenticated/price-list/'
    | '/_authenticated/profile/'
    | '/_authenticated/protectives/'
    | '/_authenticated/reports/'
    | '/_authenticated/repository/'
    | '/_authenticated/service-calls/'
    | '/_authenticated/service-packages/'
    | '/_authenticated/settings/'
    | '/_authenticated/statuses/'
    | '/_authenticated/tech-support/'
    | '/_authenticated/upgrade-packages/'
    | '/_authenticated/usage-types/'
    | '/_authenticated/users/'
    | '/_public/login/'
    | '/_authenticated/catalog/edit/$id'
    | '/_authenticated/manufacturers/edit/$id'
    | '/_authenticated/catalog/edit/'
    | '/_authenticated/price-list/advertisements/'
    | '/_authenticated/reports/car-by-years/'
    | '/_authenticated/reports/catalog-items/'
    | '/_authenticated/reports/deducted-models/'
    | '/_authenticated/reports/leading-queries/'
    | '/_authenticated/reports/low-year-exceeds-high/'
    | '/_authenticated/reports/new-models/'
    | '/_authenticated/reports/price-differences/'
    | '/_authenticated/reports/search-queries/'
    | '/_authenticated/reports/statistics/'
    | '/_authenticated/reports/subscription/'
    | '/_authenticated/price-list/advertisements/layouts/'
    | '/_authenticated/price-list/advertisements/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage-types/': {
      id: '/_authenticated/usage-types/'
      path: '/usage-types'
      fullPath: '/usage-types'
      preLoaderRoute: typeof AuthenticatedUsageTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upgrade-packages/': {
      id: '/_authenticated/upgrade-packages/'
      path: '/upgrade-packages'
      fullPath: '/upgrade-packages'
      preLoaderRoute: typeof AuthenticatedUpgradePackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tech-support/': {
      id: '/_authenticated/tech-support/'
      path: '/tech-support'
      fullPath: '/tech-support'
      preLoaderRoute: typeof AuthenticatedTechSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statuses/': {
      id: '/_authenticated/statuses/'
      path: '/statuses'
      fullPath: '/statuses'
      preLoaderRoute: typeof AuthenticatedStatusesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service-packages/': {
      id: '/_authenticated/service-packages/'
      path: '/service-packages'
      fullPath: '/service-packages'
      preLoaderRoute: typeof AuthenticatedServicePackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service-calls/': {
      id: '/_authenticated/service-calls/'
      path: '/service-calls'
      fullPath: '/service-calls'
      preLoaderRoute: typeof AuthenticatedServiceCallsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repository/': {
      id: '/_authenticated/repository/'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof AuthenticatedRepositoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/protectives/': {
      id: '/_authenticated/protectives/'
      path: '/protectives'
      fullPath: '/protectives'
      preLoaderRoute: typeof AuthenticatedProtectivesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/price-list/': {
      id: '/_authenticated/price-list/'
      path: '/price-list'
      fullPath: '/price-list'
      preLoaderRoute: typeof AuthenticatedPriceListIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owners/': {
      id: '/_authenticated/owners/'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof AuthenticatedOwnersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opinions/': {
      id: '/_authenticated/opinions/'
      path: '/opinions'
      fullPath: '/opinions'
      preLoaderRoute: typeof AuthenticatedOpinionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mileage-adjustments/': {
      id: '/_authenticated/mileage-adjustments/'
      path: '/mileage-adjustments'
      fullPath: '/mileage-adjustments'
      preLoaderRoute: typeof AuthenticatedMileageAdjustmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marks/': {
      id: '/_authenticated/marks/'
      path: '/marks'
      fullPath: '/marks'
      preLoaderRoute: typeof AuthenticatedMarksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manufacturers/': {
      id: '/_authenticated/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof AuthenticatedManufacturersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integral-extras/': {
      id: '/_authenticated/integral-extras/'
      path: '/integral-extras'
      fullPath: '/integral-extras'
      preLoaderRoute: typeof AuthenticatedIntegralExtrasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importers/': {
      id: '/_authenticated/importers/'
      path: '/importers'
      fullPath: '/importers'
      preLoaderRoute: typeof AuthenticatedImportersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gearboxes/': {
      id: '/_authenticated/gearboxes/'
      path: '/gearboxes'
      fullPath: '/gearboxes'
      preLoaderRoute: typeof AuthenticatedGearboxesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extras/': {
      id: '/_authenticated/extras/'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof AuthenticatedExtrasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engine-types/': {
      id: '/_authenticated/engine-types/'
      path: '/engine-types'
      fullPath: '/engine-types'
      preLoaderRoute: typeof AuthenticatedEngineTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drive-types/': {
      id: '/_authenticated/drive-types/'
      path: '/drive-types'
      fullPath: '/drive-types'
      preLoaderRoute: typeof AuthenticatedDriveTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/countries/': {
      id: '/_authenticated/countries/'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AuthenticatedCountriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comments-for-opinion/': {
      id: '/_authenticated/comments-for-opinion/'
      path: '/comments-for-opinion'
      fullPath: '/comments-for-opinion'
      preLoaderRoute: typeof AuthenticatedCommentsForOpinionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codes/': {
      id: '/_authenticated/codes/'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof AuthenticatedCodesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client-support/': {
      id: '/_authenticated/client-support/'
      path: '/client-support'
      fullPath: '/client-support'
      preLoaderRoute: typeof AuthenticatedClientSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/car-types/': {
      id: '/_authenticated/car-types/'
      path: '/car-types'
      fullPath: '/car-types'
      preLoaderRoute: typeof AuthenticatedCarTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/body-types/': {
      id: '/_authenticated/body-types/'
      path: '/body-types'
      fullPath: '/body-types'
      preLoaderRoute: typeof AuthenticatedBodyTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appraisers/': {
      id: '/_authenticated/appraisers/'
      path: '/appraisers'
      fullPath: '/appraisers'
      preLoaderRoute: typeof AuthenticatedAppraisersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/advertisements/': {
      id: '/_authenticated/advertisements/'
      path: '/advertisements'
      fullPath: '/advertisements'
      preLoaderRoute: typeof AuthenticatedAdvertisementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accessories/': {
      id: '/_authenticated/accessories/'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AuthenticatedAccessoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tech-support/new': {
      id: '/_authenticated/tech-support/new'
      path: '/tech-support/new'
      fullPath: '/tech-support/new'
      preLoaderRoute: typeof AuthenticatedTechSupportNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tech-support/$id': {
      id: '/_authenticated/tech-support/$id'
      path: '/tech-support/$id'
      fullPath: '/tech-support/$id'
      preLoaderRoute: typeof AuthenticatedTechSupportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/price-list/advertisements': {
      id: '/_authenticated/price-list/advertisements'
      path: '/price-list/advertisements'
      fullPath: '/price-list/advertisements'
      preLoaderRoute: typeof AuthenticatedPriceListAdvertisementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opinions/new': {
      id: '/_authenticated/opinions/new'
      path: '/opinions/new'
      fullPath: '/opinions/new'
      preLoaderRoute: typeof AuthenticatedOpinionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opinions/$id': {
      id: '/_authenticated/opinions/$id'
      path: '/opinions/$id'
      fullPath: '/opinions/$id'
      preLoaderRoute: typeof AuthenticatedOpinionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codes/sync': {
      id: '/_authenticated/codes/sync'
      path: '/codes/sync'
      fullPath: '/codes/sync'
      preLoaderRoute: typeof AuthenticatedCodesSyncRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codes/new': {
      id: '/_authenticated/codes/new'
      path: '/codes/new'
      fullPath: '/codes/new'
      preLoaderRoute: typeof AuthenticatedCodesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codes/$id': {
      id: '/_authenticated/codes/$id'
      path: '/codes/$id'
      fullPath: '/codes/$id'
      preLoaderRoute: typeof AuthenticatedCodesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client-support/$id': {
      id: '/_authenticated/client-support/$id'
      path: '/client-support/$id'
      fullPath: '/client-support/$id'
      preLoaderRoute: typeof AuthenticatedClientSupportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/prices': {
      id: '/_authenticated/catalog/prices'
      path: '/catalog/prices'
      fullPath: '/catalog/prices'
      preLoaderRoute: typeof AuthenticatedCatalogPricesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/new-car': {
      id: '/_authenticated/catalog/new-car'
      path: '/catalog/new-car'
      fullPath: '/catalog/new-car'
      preLoaderRoute: typeof AuthenticatedCatalogNewCarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$id': {
      id: '/_authenticated/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof AuthenticatedCatalogIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/subscription/': {
      id: '/_authenticated/reports/subscription/'
      path: '/subscription'
      fullPath: '/reports/subscription'
      preLoaderRoute: typeof AuthenticatedReportsSubscriptionIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/statistics/': {
      id: '/_authenticated/reports/statistics/'
      path: '/statistics'
      fullPath: '/reports/statistics'
      preLoaderRoute: typeof AuthenticatedReportsStatisticsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/search-queries/': {
      id: '/_authenticated/reports/search-queries/'
      path: '/search-queries'
      fullPath: '/reports/search-queries'
      preLoaderRoute: typeof AuthenticatedReportsSearchQueriesIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/price-differences/': {
      id: '/_authenticated/reports/price-differences/'
      path: '/price-differences'
      fullPath: '/reports/price-differences'
      preLoaderRoute: typeof AuthenticatedReportsPriceDifferencesIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/new-models/': {
      id: '/_authenticated/reports/new-models/'
      path: '/new-models'
      fullPath: '/reports/new-models'
      preLoaderRoute: typeof AuthenticatedReportsNewModelsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/low-year-exceeds-high/': {
      id: '/_authenticated/reports/low-year-exceeds-high/'
      path: '/low-year-exceeds-high'
      fullPath: '/reports/low-year-exceeds-high'
      preLoaderRoute: typeof AuthenticatedReportsLowYearExceedsHighIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/leading-queries/': {
      id: '/_authenticated/reports/leading-queries/'
      path: '/leading-queries'
      fullPath: '/reports/leading-queries'
      preLoaderRoute: typeof AuthenticatedReportsLeadingQueriesIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/deducted-models/': {
      id: '/_authenticated/reports/deducted-models/'
      path: '/deducted-models'
      fullPath: '/reports/deducted-models'
      preLoaderRoute: typeof AuthenticatedReportsDeductedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/catalog-items/': {
      id: '/_authenticated/reports/catalog-items/'
      path: '/catalog-items'
      fullPath: '/reports/catalog-items'
      preLoaderRoute: typeof AuthenticatedReportsCatalogItemsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/reports/car-by-years/': {
      id: '/_authenticated/reports/car-by-years/'
      path: '/car-by-years'
      fullPath: '/reports/car-by-years'
      preLoaderRoute: typeof AuthenticatedReportsCarByYearsIndexRouteImport
      parentRoute: typeof AuthenticatedReportsRoute
    }
    '/_authenticated/price-list/advertisements/': {
      id: '/_authenticated/price-list/advertisements/'
      path: '/'
      fullPath: '/price-list/advertisements/'
      preLoaderRoute: typeof AuthenticatedPriceListAdvertisementsIndexRouteImport
      parentRoute: typeof AuthenticatedPriceListAdvertisementsRoute
    }
    '/_authenticated/catalog/edit/': {
      id: '/_authenticated/catalog/edit/'
      path: '/catalog/edit'
      fullPath: '/catalog/edit'
      preLoaderRoute: typeof AuthenticatedCatalogEditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manufacturers/edit/$id': {
      id: '/_authenticated/manufacturers/edit/$id'
      path: '/manufacturers/edit/$id'
      fullPath: '/manufacturers/edit/$id'
      preLoaderRoute: typeof AuthenticatedManufacturersEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/edit/$id': {
      id: '/_authenticated/catalog/edit/$id'
      path: '/catalog/edit/$id'
      fullPath: '/catalog/edit/$id'
      preLoaderRoute: typeof AuthenticatedCatalogEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/price-list/advertisements/test/': {
      id: '/_authenticated/price-list/advertisements/test/'
      path: '/test'
      fullPath: '/price-list/advertisements/test'
      preLoaderRoute: typeof AuthenticatedPriceListAdvertisementsTestIndexRouteImport
      parentRoute: typeof AuthenticatedPriceListAdvertisementsRoute
    }
    '/_authenticated/price-list/advertisements/layouts/': {
      id: '/_authenticated/price-list/advertisements/layouts/'
      path: '/layouts'
      fullPath: '/price-list/advertisements/layouts'
      preLoaderRoute: typeof AuthenticatedPriceListAdvertisementsLayoutsIndexRouteImport
      parentRoute: typeof AuthenticatedPriceListAdvertisementsRoute
    }
  }
}

interface AuthenticatedReportsRouteChildren {
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedReportsCarByYearsIndexRoute: typeof AuthenticatedReportsCarByYearsIndexRoute
  AuthenticatedReportsCatalogItemsIndexRoute: typeof AuthenticatedReportsCatalogItemsIndexRoute
  AuthenticatedReportsDeductedModelsIndexRoute: typeof AuthenticatedReportsDeductedModelsIndexRoute
  AuthenticatedReportsLeadingQueriesIndexRoute: typeof AuthenticatedReportsLeadingQueriesIndexRoute
  AuthenticatedReportsLowYearExceedsHighIndexRoute: typeof AuthenticatedReportsLowYearExceedsHighIndexRoute
  AuthenticatedReportsNewModelsIndexRoute: typeof AuthenticatedReportsNewModelsIndexRoute
  AuthenticatedReportsPriceDifferencesIndexRoute: typeof AuthenticatedReportsPriceDifferencesIndexRoute
  AuthenticatedReportsSearchQueriesIndexRoute: typeof AuthenticatedReportsSearchQueriesIndexRoute
  AuthenticatedReportsStatisticsIndexRoute: typeof AuthenticatedReportsStatisticsIndexRoute
  AuthenticatedReportsSubscriptionIndexRoute: typeof AuthenticatedReportsSubscriptionIndexRoute
}

const AuthenticatedReportsRouteChildren: AuthenticatedReportsRouteChildren = {
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedReportsCarByYearsIndexRoute:
    AuthenticatedReportsCarByYearsIndexRoute,
  AuthenticatedReportsCatalogItemsIndexRoute:
    AuthenticatedReportsCatalogItemsIndexRoute,
  AuthenticatedReportsDeductedModelsIndexRoute:
    AuthenticatedReportsDeductedModelsIndexRoute,
  AuthenticatedReportsLeadingQueriesIndexRoute:
    AuthenticatedReportsLeadingQueriesIndexRoute,
  AuthenticatedReportsLowYearExceedsHighIndexRoute:
    AuthenticatedReportsLowYearExceedsHighIndexRoute,
  AuthenticatedReportsNewModelsIndexRoute:
    AuthenticatedReportsNewModelsIndexRoute,
  AuthenticatedReportsPriceDifferencesIndexRoute:
    AuthenticatedReportsPriceDifferencesIndexRoute,
  AuthenticatedReportsSearchQueriesIndexRoute:
    AuthenticatedReportsSearchQueriesIndexRoute,
  AuthenticatedReportsStatisticsIndexRoute:
    AuthenticatedReportsStatisticsIndexRoute,
  AuthenticatedReportsSubscriptionIndexRoute:
    AuthenticatedReportsSubscriptionIndexRoute,
}

const AuthenticatedReportsRouteWithChildren =
  AuthenticatedReportsRoute._addFileChildren(AuthenticatedReportsRouteChildren)

interface AuthenticatedPriceListAdvertisementsRouteChildren {
  AuthenticatedPriceListAdvertisementsIndexRoute: typeof AuthenticatedPriceListAdvertisementsIndexRoute
  AuthenticatedPriceListAdvertisementsLayoutsIndexRoute: typeof AuthenticatedPriceListAdvertisementsLayoutsIndexRoute
  AuthenticatedPriceListAdvertisementsTestIndexRoute: typeof AuthenticatedPriceListAdvertisementsTestIndexRoute
}

const AuthenticatedPriceListAdvertisementsRouteChildren: AuthenticatedPriceListAdvertisementsRouteChildren =
  {
    AuthenticatedPriceListAdvertisementsIndexRoute:
      AuthenticatedPriceListAdvertisementsIndexRoute,
    AuthenticatedPriceListAdvertisementsLayoutsIndexRoute:
      AuthenticatedPriceListAdvertisementsLayoutsIndexRoute,
    AuthenticatedPriceListAdvertisementsTestIndexRoute:
      AuthenticatedPriceListAdvertisementsTestIndexRoute,
  }

const AuthenticatedPriceListAdvertisementsRouteWithChildren =
  AuthenticatedPriceListAdvertisementsRoute._addFileChildren(
    AuthenticatedPriceListAdvertisementsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCatalogIdRoute: typeof AuthenticatedCatalogIdRoute
  AuthenticatedCatalogNewCarRoute: typeof AuthenticatedCatalogNewCarRoute
  AuthenticatedCatalogPricesRoute: typeof AuthenticatedCatalogPricesRoute
  AuthenticatedClientSupportIdRoute: typeof AuthenticatedClientSupportIdRoute
  AuthenticatedCodesIdRoute: typeof AuthenticatedCodesIdRoute
  AuthenticatedCodesNewRoute: typeof AuthenticatedCodesNewRoute
  AuthenticatedCodesSyncRoute: typeof AuthenticatedCodesSyncRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedOpinionsIdRoute: typeof AuthenticatedOpinionsIdRoute
  AuthenticatedOpinionsNewRoute: typeof AuthenticatedOpinionsNewRoute
  AuthenticatedPriceListAdvertisementsRoute: typeof AuthenticatedPriceListAdvertisementsRouteWithChildren
  AuthenticatedTechSupportIdRoute: typeof AuthenticatedTechSupportIdRoute
  AuthenticatedTechSupportNewRoute: typeof AuthenticatedTechSupportNewRoute
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedAccessoriesIndexRoute: typeof AuthenticatedAccessoriesIndexRoute
  AuthenticatedAdvertisementsIndexRoute: typeof AuthenticatedAdvertisementsIndexRoute
  AuthenticatedAppraisersIndexRoute: typeof AuthenticatedAppraisersIndexRoute
  AuthenticatedBodyTypesIndexRoute: typeof AuthenticatedBodyTypesIndexRoute
  AuthenticatedCarTypesIndexRoute: typeof AuthenticatedCarTypesIndexRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedClientSupportIndexRoute: typeof AuthenticatedClientSupportIndexRoute
  AuthenticatedCodesIndexRoute: typeof AuthenticatedCodesIndexRoute
  AuthenticatedCommentsForOpinionIndexRoute: typeof AuthenticatedCommentsForOpinionIndexRoute
  AuthenticatedCountriesIndexRoute: typeof AuthenticatedCountriesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDriveTypesIndexRoute: typeof AuthenticatedDriveTypesIndexRoute
  AuthenticatedEngineTypesIndexRoute: typeof AuthenticatedEngineTypesIndexRoute
  AuthenticatedExtrasIndexRoute: typeof AuthenticatedExtrasIndexRoute
  AuthenticatedGearboxesIndexRoute: typeof AuthenticatedGearboxesIndexRoute
  AuthenticatedImportersIndexRoute: typeof AuthenticatedImportersIndexRoute
  AuthenticatedIntegralExtrasIndexRoute: typeof AuthenticatedIntegralExtrasIndexRoute
  AuthenticatedManufacturersIndexRoute: typeof AuthenticatedManufacturersIndexRoute
  AuthenticatedMarksIndexRoute: typeof AuthenticatedMarksIndexRoute
  AuthenticatedMileageAdjustmentsIndexRoute: typeof AuthenticatedMileageAdjustmentsIndexRoute
  AuthenticatedOpinionsIndexRoute: typeof AuthenticatedOpinionsIndexRoute
  AuthenticatedOwnersIndexRoute: typeof AuthenticatedOwnersIndexRoute
  AuthenticatedPriceListIndexRoute: typeof AuthenticatedPriceListIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedProtectivesIndexRoute: typeof AuthenticatedProtectivesIndexRoute
  AuthenticatedRepositoryIndexRoute: typeof AuthenticatedRepositoryIndexRoute
  AuthenticatedServiceCallsIndexRoute: typeof AuthenticatedServiceCallsIndexRoute
  AuthenticatedServicePackagesIndexRoute: typeof AuthenticatedServicePackagesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStatusesIndexRoute: typeof AuthenticatedStatusesIndexRoute
  AuthenticatedTechSupportIndexRoute: typeof AuthenticatedTechSupportIndexRoute
  AuthenticatedUpgradePackagesIndexRoute: typeof AuthenticatedUpgradePackagesIndexRoute
  AuthenticatedUsageTypesIndexRoute: typeof AuthenticatedUsageTypesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedCatalogEditIdRoute: typeof AuthenticatedCatalogEditIdRoute
  AuthenticatedManufacturersEditIdRoute: typeof AuthenticatedManufacturersEditIdRoute
  AuthenticatedCatalogEditIndexRoute: typeof AuthenticatedCatalogEditIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedReportsRoute: AuthenticatedReportsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCatalogIdRoute: AuthenticatedCatalogIdRoute,
  AuthenticatedCatalogNewCarRoute: AuthenticatedCatalogNewCarRoute,
  AuthenticatedCatalogPricesRoute: AuthenticatedCatalogPricesRoute,
  AuthenticatedClientSupportIdRoute: AuthenticatedClientSupportIdRoute,
  AuthenticatedCodesIdRoute: AuthenticatedCodesIdRoute,
  AuthenticatedCodesNewRoute: AuthenticatedCodesNewRoute,
  AuthenticatedCodesSyncRoute: AuthenticatedCodesSyncRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedOpinionsIdRoute: AuthenticatedOpinionsIdRoute,
  AuthenticatedOpinionsNewRoute: AuthenticatedOpinionsNewRoute,
  AuthenticatedPriceListAdvertisementsRoute:
    AuthenticatedPriceListAdvertisementsRouteWithChildren,
  AuthenticatedTechSupportIdRoute: AuthenticatedTechSupportIdRoute,
  AuthenticatedTechSupportNewRoute: AuthenticatedTechSupportNewRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedAccessoriesIndexRoute: AuthenticatedAccessoriesIndexRoute,
  AuthenticatedAdvertisementsIndexRoute: AuthenticatedAdvertisementsIndexRoute,
  AuthenticatedAppraisersIndexRoute: AuthenticatedAppraisersIndexRoute,
  AuthenticatedBodyTypesIndexRoute: AuthenticatedBodyTypesIndexRoute,
  AuthenticatedCarTypesIndexRoute: AuthenticatedCarTypesIndexRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedClientSupportIndexRoute: AuthenticatedClientSupportIndexRoute,
  AuthenticatedCodesIndexRoute: AuthenticatedCodesIndexRoute,
  AuthenticatedCommentsForOpinionIndexRoute:
    AuthenticatedCommentsForOpinionIndexRoute,
  AuthenticatedCountriesIndexRoute: AuthenticatedCountriesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDriveTypesIndexRoute: AuthenticatedDriveTypesIndexRoute,
  AuthenticatedEngineTypesIndexRoute: AuthenticatedEngineTypesIndexRoute,
  AuthenticatedExtrasIndexRoute: AuthenticatedExtrasIndexRoute,
  AuthenticatedGearboxesIndexRoute: AuthenticatedGearboxesIndexRoute,
  AuthenticatedImportersIndexRoute: AuthenticatedImportersIndexRoute,
  AuthenticatedIntegralExtrasIndexRoute: AuthenticatedIntegralExtrasIndexRoute,
  AuthenticatedManufacturersIndexRoute: AuthenticatedManufacturersIndexRoute,
  AuthenticatedMarksIndexRoute: AuthenticatedMarksIndexRoute,
  AuthenticatedMileageAdjustmentsIndexRoute:
    AuthenticatedMileageAdjustmentsIndexRoute,
  AuthenticatedOpinionsIndexRoute: AuthenticatedOpinionsIndexRoute,
  AuthenticatedOwnersIndexRoute: AuthenticatedOwnersIndexRoute,
  AuthenticatedPriceListIndexRoute: AuthenticatedPriceListIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedProtectivesIndexRoute: AuthenticatedProtectivesIndexRoute,
  AuthenticatedRepositoryIndexRoute: AuthenticatedRepositoryIndexRoute,
  AuthenticatedServiceCallsIndexRoute: AuthenticatedServiceCallsIndexRoute,
  AuthenticatedServicePackagesIndexRoute:
    AuthenticatedServicePackagesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStatusesIndexRoute: AuthenticatedStatusesIndexRoute,
  AuthenticatedTechSupportIndexRoute: AuthenticatedTechSupportIndexRoute,
  AuthenticatedUpgradePackagesIndexRoute:
    AuthenticatedUpgradePackagesIndexRoute,
  AuthenticatedUsageTypesIndexRoute: AuthenticatedUsageTypesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedCatalogEditIdRoute: AuthenticatedCatalogEditIdRoute,
  AuthenticatedManufacturersEditIdRoute: AuthenticatedManufacturersEditIdRoute,
  AuthenticatedCatalogEditIndexRoute: AuthenticatedCatalogEditIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
