/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthenticatedValuesIndexRouteImport } from './routes/_authenticated/values/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUsageTypesIndexRouteImport } from './routes/_authenticated/usage-types/index'
import { Route as AuthenticatedUpgradePackagesIndexRouteImport } from './routes/_authenticated/upgrade-packages/index'
import { Route as AuthenticatedTechSupportIndexRouteImport } from './routes/_authenticated/tech-support/index'
import { Route as AuthenticatedStatusesIndexRouteImport } from './routes/_authenticated/statuses/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicePackagesIndexRouteImport } from './routes/_authenticated/service-packages/index'
import { Route as AuthenticatedServiceCallsIndexRouteImport } from './routes/_authenticated/service-calls/index'
import { Route as AuthenticatedRepositoryIndexRouteImport } from './routes/_authenticated/repository/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProtectivesIndexRouteImport } from './routes/_authenticated/protectives/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedPriceListIndexRouteImport } from './routes/_authenticated/price-list/index'
import { Route as AuthenticatedOwnersIndexRouteImport } from './routes/_authenticated/owners/index'
import { Route as AuthenticatedOpinionsIndexRouteImport } from './routes/_authenticated/opinions/index'
import { Route as AuthenticatedMileageAdjustmentsIndexRouteImport } from './routes/_authenticated/mileage-adjustments/index'
import { Route as AuthenticatedManufacturersIndexRouteImport } from './routes/_authenticated/manufacturers/index'
import { Route as AuthenticatedIntegralExtrasIndexRouteImport } from './routes/_authenticated/integral-extras/index'
import { Route as AuthenticatedImportersIndexRouteImport } from './routes/_authenticated/importers/index'
import { Route as AuthenticatedGearboxesIndexRouteImport } from './routes/_authenticated/gearboxes/index'
import { Route as AuthenticatedExtrasIndexRouteImport } from './routes/_authenticated/extras/index'
import { Route as AuthenticatedEngineTypesIndexRouteImport } from './routes/_authenticated/engine-types/index'
import { Route as AuthenticatedDriveTypesIndexRouteImport } from './routes/_authenticated/drive-types/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCountriesIndexRouteImport } from './routes/_authenticated/countries/index'
import { Route as AuthenticatedCommentsForOpinionIndexRouteImport } from './routes/_authenticated/comments-for-opinion/index'
import { Route as AuthenticatedCodesIndexRouteImport } from './routes/_authenticated/codes/index'
import { Route as AuthenticatedClientSupportIndexRouteImport } from './routes/_authenticated/client-support/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedCatalogIndexRouteImport } from './routes/_authenticated/catalog/index'
import { Route as AuthenticatedCarTypesIndexRouteImport } from './routes/_authenticated/car-types/index'
import { Route as AuthenticatedCarPropertiesIndexRouteImport } from './routes/_authenticated/car-properties/index'
import { Route as AuthenticatedCarMarksIndexRouteImport } from './routes/_authenticated/car-marks/index'
import { Route as AuthenticatedAppraisersIndexRouteImport } from './routes/_authenticated/appraisers/index'
import { Route as AuthenticatedAdvertisementsIndexRouteImport } from './routes/_authenticated/advertisements/index'
import { Route as AuthenticatedAccessoriesIndexRouteImport } from './routes/_authenticated/accessories/index'
import { Route as AuthenticatedOpinionsNewRouteImport } from './routes/_authenticated/opinions/new'
import { Route as AuthenticatedOpinionsIdRouteImport } from './routes/_authenticated/opinions/$id'
import { Route as AuthenticatedCustomersNewRouteImport } from './routes/_authenticated/customers/new'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers/$id'
import { Route as AuthenticatedCatalogNewCarRouteImport } from './routes/_authenticated/catalog/new-car'
import { Route as AuthenticatedCatalogIdRouteImport } from './routes/_authenticated/catalog/$id'
import { Route as AuthenticatedPriceListAdvertisementsIndexRouteImport } from './routes/_authenticated/price-list/advertisements/index'
import { Route as AuthenticatedManufacturersEditIdRouteImport } from './routes/_authenticated/manufacturers/edit/$id'
import { Route as AuthenticatedCatalogEditIdRouteImport } from './routes/_authenticated/catalog/edit/$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedValuesIndexRoute =
  AuthenticatedValuesIndexRouteImport.update({
    id: '/values/',
    path: '/values/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsageTypesIndexRoute =
  AuthenticatedUsageTypesIndexRouteImport.update({
    id: '/usage-types/',
    path: '/usage-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUpgradePackagesIndexRoute =
  AuthenticatedUpgradePackagesIndexRouteImport.update({
    id: '/upgrade-packages/',
    path: '/upgrade-packages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTechSupportIndexRoute =
  AuthenticatedTechSupportIndexRouteImport.update({
    id: '/tech-support/',
    path: '/tech-support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStatusesIndexRoute =
  AuthenticatedStatusesIndexRouteImport.update({
    id: '/statuses/',
    path: '/statuses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicePackagesIndexRoute =
  AuthenticatedServicePackagesIndexRouteImport.update({
    id: '/service-packages/',
    path: '/service-packages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServiceCallsIndexRoute =
  AuthenticatedServiceCallsIndexRouteImport.update({
    id: '/service-calls/',
    path: '/service-calls/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRepositoryIndexRoute =
  AuthenticatedRepositoryIndexRouteImport.update({
    id: '/repository/',
    path: '/repository/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProtectivesIndexRoute =
  AuthenticatedProtectivesIndexRouteImport.update({
    id: '/protectives/',
    path: '/protectives/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPriceListIndexRoute =
  AuthenticatedPriceListIndexRouteImport.update({
    id: '/price-list/',
    path: '/price-list/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnersIndexRoute =
  AuthenticatedOwnersIndexRouteImport.update({
    id: '/owners/',
    path: '/owners/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpinionsIndexRoute =
  AuthenticatedOpinionsIndexRouteImport.update({
    id: '/opinions/',
    path: '/opinions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMileageAdjustmentsIndexRoute =
  AuthenticatedMileageAdjustmentsIndexRouteImport.update({
    id: '/mileage-adjustments/',
    path: '/mileage-adjustments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManufacturersIndexRoute =
  AuthenticatedManufacturersIndexRouteImport.update({
    id: '/manufacturers/',
    path: '/manufacturers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegralExtrasIndexRoute =
  AuthenticatedIntegralExtrasIndexRouteImport.update({
    id: '/integral-extras/',
    path: '/integral-extras/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportersIndexRoute =
  AuthenticatedImportersIndexRouteImport.update({
    id: '/importers/',
    path: '/importers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGearboxesIndexRoute =
  AuthenticatedGearboxesIndexRouteImport.update({
    id: '/gearboxes/',
    path: '/gearboxes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtrasIndexRoute =
  AuthenticatedExtrasIndexRouteImport.update({
    id: '/extras/',
    path: '/extras/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEngineTypesIndexRoute =
  AuthenticatedEngineTypesIndexRouteImport.update({
    id: '/engine-types/',
    path: '/engine-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDriveTypesIndexRoute =
  AuthenticatedDriveTypesIndexRouteImport.update({
    id: '/drive-types/',
    path: '/drive-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountriesIndexRoute =
  AuthenticatedCountriesIndexRouteImport.update({
    id: '/countries/',
    path: '/countries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommentsForOpinionIndexRoute =
  AuthenticatedCommentsForOpinionIndexRouteImport.update({
    id: '/comments-for-opinion/',
    path: '/comments-for-opinion/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCodesIndexRoute = AuthenticatedCodesIndexRouteImport.update({
  id: '/codes/',
  path: '/codes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientSupportIndexRoute =
  AuthenticatedClientSupportIndexRouteImport.update({
    id: '/client-support/',
    path: '/client-support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogIndexRoute =
  AuthenticatedCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarTypesIndexRoute =
  AuthenticatedCarTypesIndexRouteImport.update({
    id: '/car-types/',
    path: '/car-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarPropertiesIndexRoute =
  AuthenticatedCarPropertiesIndexRouteImport.update({
    id: '/car-properties/',
    path: '/car-properties/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCarMarksIndexRoute =
  AuthenticatedCarMarksIndexRouteImport.update({
    id: '/car-marks/',
    path: '/car-marks/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppraisersIndexRoute =
  AuthenticatedAppraisersIndexRouteImport.update({
    id: '/appraisers/',
    path: '/appraisers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdvertisementsIndexRoute =
  AuthenticatedAdvertisementsIndexRouteImport.update({
    id: '/advertisements/',
    path: '/advertisements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccessoriesIndexRoute =
  AuthenticatedAccessoriesIndexRouteImport.update({
    id: '/accessories/',
    path: '/accessories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpinionsNewRoute =
  AuthenticatedOpinionsNewRouteImport.update({
    id: '/opinions/new',
    path: '/opinions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpinionsIdRoute = AuthenticatedOpinionsIdRouteImport.update({
  id: '/opinions/$id',
  path: '/opinions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersNewRoute =
  AuthenticatedCustomersNewRouteImport.update({
    id: '/customers/new',
    path: '/customers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogNewCarRoute =
  AuthenticatedCatalogNewCarRouteImport.update({
    id: '/catalog/new-car',
    path: '/catalog/new-car',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogIdRoute = AuthenticatedCatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPriceListAdvertisementsIndexRoute =
  AuthenticatedPriceListAdvertisementsIndexRouteImport.update({
    id: '/price-list/advertisements/',
    path: '/price-list/advertisements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManufacturersEditIdRoute =
  AuthenticatedManufacturersEditIdRouteImport.update({
    id: '/manufacturers/edit/$id',
    path: '/manufacturers/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogEditIdRoute =
  AuthenticatedCatalogEditIdRouteImport.update({
    id: '/catalog/edit/$id',
    path: '/catalog/edit/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/catalog/$id': typeof AuthenticatedCatalogIdRoute
  '/catalog/new-car': typeof AuthenticatedCatalogNewCarRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/opinions/$id': typeof AuthenticatedOpinionsIdRoute
  '/opinions/new': typeof AuthenticatedOpinionsNewRoute
  '/accessories': typeof AuthenticatedAccessoriesIndexRoute
  '/advertisements': typeof AuthenticatedAdvertisementsIndexRoute
  '/appraisers': typeof AuthenticatedAppraisersIndexRoute
  '/car-marks': typeof AuthenticatedCarMarksIndexRoute
  '/car-properties': typeof AuthenticatedCarPropertiesIndexRoute
  '/car-types': typeof AuthenticatedCarTypesIndexRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/client-support': typeof AuthenticatedClientSupportIndexRoute
  '/codes': typeof AuthenticatedCodesIndexRoute
  '/comments-for-opinion': typeof AuthenticatedCommentsForOpinionIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drive-types': typeof AuthenticatedDriveTypesIndexRoute
  '/engine-types': typeof AuthenticatedEngineTypesIndexRoute
  '/extras': typeof AuthenticatedExtrasIndexRoute
  '/gearboxes': typeof AuthenticatedGearboxesIndexRoute
  '/importers': typeof AuthenticatedImportersIndexRoute
  '/integral-extras': typeof AuthenticatedIntegralExtrasIndexRoute
  '/manufacturers': typeof AuthenticatedManufacturersIndexRoute
  '/mileage-adjustments': typeof AuthenticatedMileageAdjustmentsIndexRoute
  '/opinions': typeof AuthenticatedOpinionsIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/price-list': typeof AuthenticatedPriceListIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/protectives': typeof AuthenticatedProtectivesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/repository': typeof AuthenticatedRepositoryIndexRoute
  '/service-calls': typeof AuthenticatedServiceCallsIndexRoute
  '/service-packages': typeof AuthenticatedServicePackagesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/statuses': typeof AuthenticatedStatusesIndexRoute
  '/tech-support': typeof AuthenticatedTechSupportIndexRoute
  '/upgrade-packages': typeof AuthenticatedUpgradePackagesIndexRoute
  '/usage-types': typeof AuthenticatedUsageTypesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/values': typeof AuthenticatedValuesIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/catalog/edit/$id': typeof AuthenticatedCatalogEditIdRoute
  '/manufacturers/edit/$id': typeof AuthenticatedManufacturersEditIdRoute
  '/price-list/advertisements': typeof AuthenticatedPriceListAdvertisementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/catalog/$id': typeof AuthenticatedCatalogIdRoute
  '/catalog/new-car': typeof AuthenticatedCatalogNewCarRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/new': typeof AuthenticatedCustomersNewRoute
  '/opinions/$id': typeof AuthenticatedOpinionsIdRoute
  '/opinions/new': typeof AuthenticatedOpinionsNewRoute
  '/accessories': typeof AuthenticatedAccessoriesIndexRoute
  '/advertisements': typeof AuthenticatedAdvertisementsIndexRoute
  '/appraisers': typeof AuthenticatedAppraisersIndexRoute
  '/car-marks': typeof AuthenticatedCarMarksIndexRoute
  '/car-properties': typeof AuthenticatedCarPropertiesIndexRoute
  '/car-types': typeof AuthenticatedCarTypesIndexRoute
  '/catalog': typeof AuthenticatedCatalogIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/client-support': typeof AuthenticatedClientSupportIndexRoute
  '/codes': typeof AuthenticatedCodesIndexRoute
  '/comments-for-opinion': typeof AuthenticatedCommentsForOpinionIndexRoute
  '/countries': typeof AuthenticatedCountriesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/drive-types': typeof AuthenticatedDriveTypesIndexRoute
  '/engine-types': typeof AuthenticatedEngineTypesIndexRoute
  '/extras': typeof AuthenticatedExtrasIndexRoute
  '/gearboxes': typeof AuthenticatedGearboxesIndexRoute
  '/importers': typeof AuthenticatedImportersIndexRoute
  '/integral-extras': typeof AuthenticatedIntegralExtrasIndexRoute
  '/manufacturers': typeof AuthenticatedManufacturersIndexRoute
  '/mileage-adjustments': typeof AuthenticatedMileageAdjustmentsIndexRoute
  '/opinions': typeof AuthenticatedOpinionsIndexRoute
  '/owners': typeof AuthenticatedOwnersIndexRoute
  '/price-list': typeof AuthenticatedPriceListIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/protectives': typeof AuthenticatedProtectivesIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/repository': typeof AuthenticatedRepositoryIndexRoute
  '/service-calls': typeof AuthenticatedServiceCallsIndexRoute
  '/service-packages': typeof AuthenticatedServicePackagesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/statuses': typeof AuthenticatedStatusesIndexRoute
  '/tech-support': typeof AuthenticatedTechSupportIndexRoute
  '/upgrade-packages': typeof AuthenticatedUpgradePackagesIndexRoute
  '/usage-types': typeof AuthenticatedUsageTypesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/values': typeof AuthenticatedValuesIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/catalog/edit/$id': typeof AuthenticatedCatalogEditIdRoute
  '/manufacturers/edit/$id': typeof AuthenticatedManufacturersEditIdRoute
  '/price-list/advertisements': typeof AuthenticatedPriceListAdvertisementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/catalog/$id': typeof AuthenticatedCatalogIdRoute
  '/_authenticated/catalog/new-car': typeof AuthenticatedCatalogNewCarRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/customers/new': typeof AuthenticatedCustomersNewRoute
  '/_authenticated/opinions/$id': typeof AuthenticatedOpinionsIdRoute
  '/_authenticated/opinions/new': typeof AuthenticatedOpinionsNewRoute
  '/_authenticated/accessories/': typeof AuthenticatedAccessoriesIndexRoute
  '/_authenticated/advertisements/': typeof AuthenticatedAdvertisementsIndexRoute
  '/_authenticated/appraisers/': typeof AuthenticatedAppraisersIndexRoute
  '/_authenticated/car-marks/': typeof AuthenticatedCarMarksIndexRoute
  '/_authenticated/car-properties/': typeof AuthenticatedCarPropertiesIndexRoute
  '/_authenticated/car-types/': typeof AuthenticatedCarTypesIndexRoute
  '/_authenticated/catalog/': typeof AuthenticatedCatalogIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/client-support/': typeof AuthenticatedClientSupportIndexRoute
  '/_authenticated/codes/': typeof AuthenticatedCodesIndexRoute
  '/_authenticated/comments-for-opinion/': typeof AuthenticatedCommentsForOpinionIndexRoute
  '/_authenticated/countries/': typeof AuthenticatedCountriesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/drive-types/': typeof AuthenticatedDriveTypesIndexRoute
  '/_authenticated/engine-types/': typeof AuthenticatedEngineTypesIndexRoute
  '/_authenticated/extras/': typeof AuthenticatedExtrasIndexRoute
  '/_authenticated/gearboxes/': typeof AuthenticatedGearboxesIndexRoute
  '/_authenticated/importers/': typeof AuthenticatedImportersIndexRoute
  '/_authenticated/integral-extras/': typeof AuthenticatedIntegralExtrasIndexRoute
  '/_authenticated/manufacturers/': typeof AuthenticatedManufacturersIndexRoute
  '/_authenticated/mileage-adjustments/': typeof AuthenticatedMileageAdjustmentsIndexRoute
  '/_authenticated/opinions/': typeof AuthenticatedOpinionsIndexRoute
  '/_authenticated/owners/': typeof AuthenticatedOwnersIndexRoute
  '/_authenticated/price-list/': typeof AuthenticatedPriceListIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/protectives/': typeof AuthenticatedProtectivesIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/repository/': typeof AuthenticatedRepositoryIndexRoute
  '/_authenticated/service-calls/': typeof AuthenticatedServiceCallsIndexRoute
  '/_authenticated/service-packages/': typeof AuthenticatedServicePackagesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/statuses/': typeof AuthenticatedStatusesIndexRoute
  '/_authenticated/tech-support/': typeof AuthenticatedTechSupportIndexRoute
  '/_authenticated/upgrade-packages/': typeof AuthenticatedUpgradePackagesIndexRoute
  '/_authenticated/usage-types/': typeof AuthenticatedUsageTypesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/values/': typeof AuthenticatedValuesIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_authenticated/catalog/edit/$id': typeof AuthenticatedCatalogEditIdRoute
  '/_authenticated/manufacturers/edit/$id': typeof AuthenticatedManufacturersEditIdRoute
  '/_authenticated/price-list/advertisements/': typeof AuthenticatedPriceListAdvertisementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog/$id'
    | '/catalog/new-car'
    | '/customers/$id'
    | '/customers/new'
    | '/opinions/$id'
    | '/opinions/new'
    | '/accessories'
    | '/advertisements'
    | '/appraisers'
    | '/car-marks'
    | '/car-properties'
    | '/car-types'
    | '/catalog'
    | '/categories'
    | '/client-support'
    | '/codes'
    | '/comments-for-opinion'
    | '/countries'
    | '/customers'
    | '/drive-types'
    | '/engine-types'
    | '/extras'
    | '/gearboxes'
    | '/importers'
    | '/integral-extras'
    | '/manufacturers'
    | '/mileage-adjustments'
    | '/opinions'
    | '/owners'
    | '/price-list'
    | '/profile'
    | '/protectives'
    | '/reports'
    | '/repository'
    | '/service-calls'
    | '/service-packages'
    | '/settings'
    | '/statuses'
    | '/tech-support'
    | '/upgrade-packages'
    | '/usage-types'
    | '/users'
    | '/values'
    | '/login'
    | '/catalog/edit/$id'
    | '/manufacturers/edit/$id'
    | '/price-list/advertisements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog/$id'
    | '/catalog/new-car'
    | '/customers/$id'
    | '/customers/new'
    | '/opinions/$id'
    | '/opinions/new'
    | '/accessories'
    | '/advertisements'
    | '/appraisers'
    | '/car-marks'
    | '/car-properties'
    | '/car-types'
    | '/catalog'
    | '/categories'
    | '/client-support'
    | '/codes'
    | '/comments-for-opinion'
    | '/countries'
    | '/customers'
    | '/drive-types'
    | '/engine-types'
    | '/extras'
    | '/gearboxes'
    | '/importers'
    | '/integral-extras'
    | '/manufacturers'
    | '/mileage-adjustments'
    | '/opinions'
    | '/owners'
    | '/price-list'
    | '/profile'
    | '/protectives'
    | '/reports'
    | '/repository'
    | '/service-calls'
    | '/service-packages'
    | '/settings'
    | '/statuses'
    | '/tech-support'
    | '/upgrade-packages'
    | '/usage-types'
    | '/users'
    | '/values'
    | '/login'
    | '/catalog/edit/$id'
    | '/manufacturers/edit/$id'
    | '/price-list/advertisements'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/'
    | '/_authenticated/catalog/$id'
    | '/_authenticated/catalog/new-car'
    | '/_authenticated/customers/$id'
    | '/_authenticated/customers/new'
    | '/_authenticated/opinions/$id'
    | '/_authenticated/opinions/new'
    | '/_authenticated/accessories/'
    | '/_authenticated/advertisements/'
    | '/_authenticated/appraisers/'
    | '/_authenticated/car-marks/'
    | '/_authenticated/car-properties/'
    | '/_authenticated/car-types/'
    | '/_authenticated/catalog/'
    | '/_authenticated/categories/'
    | '/_authenticated/client-support/'
    | '/_authenticated/codes/'
    | '/_authenticated/comments-for-opinion/'
    | '/_authenticated/countries/'
    | '/_authenticated/customers/'
    | '/_authenticated/drive-types/'
    | '/_authenticated/engine-types/'
    | '/_authenticated/extras/'
    | '/_authenticated/gearboxes/'
    | '/_authenticated/importers/'
    | '/_authenticated/integral-extras/'
    | '/_authenticated/manufacturers/'
    | '/_authenticated/mileage-adjustments/'
    | '/_authenticated/opinions/'
    | '/_authenticated/owners/'
    | '/_authenticated/price-list/'
    | '/_authenticated/profile/'
    | '/_authenticated/protectives/'
    | '/_authenticated/reports/'
    | '/_authenticated/repository/'
    | '/_authenticated/service-calls/'
    | '/_authenticated/service-packages/'
    | '/_authenticated/settings/'
    | '/_authenticated/statuses/'
    | '/_authenticated/tech-support/'
    | '/_authenticated/upgrade-packages/'
    | '/_authenticated/usage-types/'
    | '/_authenticated/users/'
    | '/_authenticated/values/'
    | '/_public/login/'
    | '/_authenticated/catalog/edit/$id'
    | '/_authenticated/manufacturers/edit/$id'
    | '/_authenticated/price-list/advertisements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/values/': {
      id: '/_authenticated/values/'
      path: '/values'
      fullPath: '/values'
      preLoaderRoute: typeof AuthenticatedValuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/usage-types/': {
      id: '/_authenticated/usage-types/'
      path: '/usage-types'
      fullPath: '/usage-types'
      preLoaderRoute: typeof AuthenticatedUsageTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upgrade-packages/': {
      id: '/_authenticated/upgrade-packages/'
      path: '/upgrade-packages'
      fullPath: '/upgrade-packages'
      preLoaderRoute: typeof AuthenticatedUpgradePackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tech-support/': {
      id: '/_authenticated/tech-support/'
      path: '/tech-support'
      fullPath: '/tech-support'
      preLoaderRoute: typeof AuthenticatedTechSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statuses/': {
      id: '/_authenticated/statuses/'
      path: '/statuses'
      fullPath: '/statuses'
      preLoaderRoute: typeof AuthenticatedStatusesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service-packages/': {
      id: '/_authenticated/service-packages/'
      path: '/service-packages'
      fullPath: '/service-packages'
      preLoaderRoute: typeof AuthenticatedServicePackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/service-calls/': {
      id: '/_authenticated/service-calls/'
      path: '/service-calls'
      fullPath: '/service-calls'
      preLoaderRoute: typeof AuthenticatedServiceCallsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repository/': {
      id: '/_authenticated/repository/'
      path: '/repository'
      fullPath: '/repository'
      preLoaderRoute: typeof AuthenticatedRepositoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/protectives/': {
      id: '/_authenticated/protectives/'
      path: '/protectives'
      fullPath: '/protectives'
      preLoaderRoute: typeof AuthenticatedProtectivesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/price-list/': {
      id: '/_authenticated/price-list/'
      path: '/price-list'
      fullPath: '/price-list'
      preLoaderRoute: typeof AuthenticatedPriceListIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owners/': {
      id: '/_authenticated/owners/'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof AuthenticatedOwnersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opinions/': {
      id: '/_authenticated/opinions/'
      path: '/opinions'
      fullPath: '/opinions'
      preLoaderRoute: typeof AuthenticatedOpinionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mileage-adjustments/': {
      id: '/_authenticated/mileage-adjustments/'
      path: '/mileage-adjustments'
      fullPath: '/mileage-adjustments'
      preLoaderRoute: typeof AuthenticatedMileageAdjustmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manufacturers/': {
      id: '/_authenticated/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers'
      preLoaderRoute: typeof AuthenticatedManufacturersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integral-extras/': {
      id: '/_authenticated/integral-extras/'
      path: '/integral-extras'
      fullPath: '/integral-extras'
      preLoaderRoute: typeof AuthenticatedIntegralExtrasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/importers/': {
      id: '/_authenticated/importers/'
      path: '/importers'
      fullPath: '/importers'
      preLoaderRoute: typeof AuthenticatedImportersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gearboxes/': {
      id: '/_authenticated/gearboxes/'
      path: '/gearboxes'
      fullPath: '/gearboxes'
      preLoaderRoute: typeof AuthenticatedGearboxesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extras/': {
      id: '/_authenticated/extras/'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof AuthenticatedExtrasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/engine-types/': {
      id: '/_authenticated/engine-types/'
      path: '/engine-types'
      fullPath: '/engine-types'
      preLoaderRoute: typeof AuthenticatedEngineTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drive-types/': {
      id: '/_authenticated/drive-types/'
      path: '/drive-types'
      fullPath: '/drive-types'
      preLoaderRoute: typeof AuthenticatedDriveTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/countries/': {
      id: '/_authenticated/countries/'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AuthenticatedCountriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comments-for-opinion/': {
      id: '/_authenticated/comments-for-opinion/'
      path: '/comments-for-opinion'
      fullPath: '/comments-for-opinion'
      preLoaderRoute: typeof AuthenticatedCommentsForOpinionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/codes/': {
      id: '/_authenticated/codes/'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof AuthenticatedCodesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client-support/': {
      id: '/_authenticated/client-support/'
      path: '/client-support'
      fullPath: '/client-support'
      preLoaderRoute: typeof AuthenticatedClientSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/': {
      id: '/_authenticated/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/car-types/': {
      id: '/_authenticated/car-types/'
      path: '/car-types'
      fullPath: '/car-types'
      preLoaderRoute: typeof AuthenticatedCarTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/car-properties/': {
      id: '/_authenticated/car-properties/'
      path: '/car-properties'
      fullPath: '/car-properties'
      preLoaderRoute: typeof AuthenticatedCarPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/car-marks/': {
      id: '/_authenticated/car-marks/'
      path: '/car-marks'
      fullPath: '/car-marks'
      preLoaderRoute: typeof AuthenticatedCarMarksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/appraisers/': {
      id: '/_authenticated/appraisers/'
      path: '/appraisers'
      fullPath: '/appraisers'
      preLoaderRoute: typeof AuthenticatedAppraisersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/advertisements/': {
      id: '/_authenticated/advertisements/'
      path: '/advertisements'
      fullPath: '/advertisements'
      preLoaderRoute: typeof AuthenticatedAdvertisementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accessories/': {
      id: '/_authenticated/accessories/'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AuthenticatedAccessoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opinions/new': {
      id: '/_authenticated/opinions/new'
      path: '/opinions/new'
      fullPath: '/opinions/new'
      preLoaderRoute: typeof AuthenticatedOpinionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opinions/$id': {
      id: '/_authenticated/opinions/$id'
      path: '/opinions/$id'
      fullPath: '/opinions/$id'
      preLoaderRoute: typeof AuthenticatedOpinionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/new': {
      id: '/_authenticated/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedCustomersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/new-car': {
      id: '/_authenticated/catalog/new-car'
      path: '/catalog/new-car'
      fullPath: '/catalog/new-car'
      preLoaderRoute: typeof AuthenticatedCatalogNewCarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/$id': {
      id: '/_authenticated/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof AuthenticatedCatalogIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/price-list/advertisements/': {
      id: '/_authenticated/price-list/advertisements/'
      path: '/price-list/advertisements'
      fullPath: '/price-list/advertisements'
      preLoaderRoute: typeof AuthenticatedPriceListAdvertisementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manufacturers/edit/$id': {
      id: '/_authenticated/manufacturers/edit/$id'
      path: '/manufacturers/edit/$id'
      fullPath: '/manufacturers/edit/$id'
      preLoaderRoute: typeof AuthenticatedManufacturersEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/edit/$id': {
      id: '/_authenticated/catalog/edit/$id'
      path: '/catalog/edit/$id'
      fullPath: '/catalog/edit/$id'
      preLoaderRoute: typeof AuthenticatedCatalogEditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCatalogIdRoute: typeof AuthenticatedCatalogIdRoute
  AuthenticatedCatalogNewCarRoute: typeof AuthenticatedCatalogNewCarRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersNewRoute: typeof AuthenticatedCustomersNewRoute
  AuthenticatedOpinionsIdRoute: typeof AuthenticatedOpinionsIdRoute
  AuthenticatedOpinionsNewRoute: typeof AuthenticatedOpinionsNewRoute
  AuthenticatedAccessoriesIndexRoute: typeof AuthenticatedAccessoriesIndexRoute
  AuthenticatedAdvertisementsIndexRoute: typeof AuthenticatedAdvertisementsIndexRoute
  AuthenticatedAppraisersIndexRoute: typeof AuthenticatedAppraisersIndexRoute
  AuthenticatedCarMarksIndexRoute: typeof AuthenticatedCarMarksIndexRoute
  AuthenticatedCarPropertiesIndexRoute: typeof AuthenticatedCarPropertiesIndexRoute
  AuthenticatedCarTypesIndexRoute: typeof AuthenticatedCarTypesIndexRoute
  AuthenticatedCatalogIndexRoute: typeof AuthenticatedCatalogIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedClientSupportIndexRoute: typeof AuthenticatedClientSupportIndexRoute
  AuthenticatedCodesIndexRoute: typeof AuthenticatedCodesIndexRoute
  AuthenticatedCommentsForOpinionIndexRoute: typeof AuthenticatedCommentsForOpinionIndexRoute
  AuthenticatedCountriesIndexRoute: typeof AuthenticatedCountriesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDriveTypesIndexRoute: typeof AuthenticatedDriveTypesIndexRoute
  AuthenticatedEngineTypesIndexRoute: typeof AuthenticatedEngineTypesIndexRoute
  AuthenticatedExtrasIndexRoute: typeof AuthenticatedExtrasIndexRoute
  AuthenticatedGearboxesIndexRoute: typeof AuthenticatedGearboxesIndexRoute
  AuthenticatedImportersIndexRoute: typeof AuthenticatedImportersIndexRoute
  AuthenticatedIntegralExtrasIndexRoute: typeof AuthenticatedIntegralExtrasIndexRoute
  AuthenticatedManufacturersIndexRoute: typeof AuthenticatedManufacturersIndexRoute
  AuthenticatedMileageAdjustmentsIndexRoute: typeof AuthenticatedMileageAdjustmentsIndexRoute
  AuthenticatedOpinionsIndexRoute: typeof AuthenticatedOpinionsIndexRoute
  AuthenticatedOwnersIndexRoute: typeof AuthenticatedOwnersIndexRoute
  AuthenticatedPriceListIndexRoute: typeof AuthenticatedPriceListIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedProtectivesIndexRoute: typeof AuthenticatedProtectivesIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRepositoryIndexRoute: typeof AuthenticatedRepositoryIndexRoute
  AuthenticatedServiceCallsIndexRoute: typeof AuthenticatedServiceCallsIndexRoute
  AuthenticatedServicePackagesIndexRoute: typeof AuthenticatedServicePackagesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStatusesIndexRoute: typeof AuthenticatedStatusesIndexRoute
  AuthenticatedTechSupportIndexRoute: typeof AuthenticatedTechSupportIndexRoute
  AuthenticatedUpgradePackagesIndexRoute: typeof AuthenticatedUpgradePackagesIndexRoute
  AuthenticatedUsageTypesIndexRoute: typeof AuthenticatedUsageTypesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedValuesIndexRoute: typeof AuthenticatedValuesIndexRoute
  AuthenticatedCatalogEditIdRoute: typeof AuthenticatedCatalogEditIdRoute
  AuthenticatedManufacturersEditIdRoute: typeof AuthenticatedManufacturersEditIdRoute
  AuthenticatedPriceListAdvertisementsIndexRoute: typeof AuthenticatedPriceListAdvertisementsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCatalogIdRoute: AuthenticatedCatalogIdRoute,
  AuthenticatedCatalogNewCarRoute: AuthenticatedCatalogNewCarRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedCustomersNewRoute: AuthenticatedCustomersNewRoute,
  AuthenticatedOpinionsIdRoute: AuthenticatedOpinionsIdRoute,
  AuthenticatedOpinionsNewRoute: AuthenticatedOpinionsNewRoute,
  AuthenticatedAccessoriesIndexRoute: AuthenticatedAccessoriesIndexRoute,
  AuthenticatedAdvertisementsIndexRoute: AuthenticatedAdvertisementsIndexRoute,
  AuthenticatedAppraisersIndexRoute: AuthenticatedAppraisersIndexRoute,
  AuthenticatedCarMarksIndexRoute: AuthenticatedCarMarksIndexRoute,
  AuthenticatedCarPropertiesIndexRoute: AuthenticatedCarPropertiesIndexRoute,
  AuthenticatedCarTypesIndexRoute: AuthenticatedCarTypesIndexRoute,
  AuthenticatedCatalogIndexRoute: AuthenticatedCatalogIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedClientSupportIndexRoute: AuthenticatedClientSupportIndexRoute,
  AuthenticatedCodesIndexRoute: AuthenticatedCodesIndexRoute,
  AuthenticatedCommentsForOpinionIndexRoute:
    AuthenticatedCommentsForOpinionIndexRoute,
  AuthenticatedCountriesIndexRoute: AuthenticatedCountriesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDriveTypesIndexRoute: AuthenticatedDriveTypesIndexRoute,
  AuthenticatedEngineTypesIndexRoute: AuthenticatedEngineTypesIndexRoute,
  AuthenticatedExtrasIndexRoute: AuthenticatedExtrasIndexRoute,
  AuthenticatedGearboxesIndexRoute: AuthenticatedGearboxesIndexRoute,
  AuthenticatedImportersIndexRoute: AuthenticatedImportersIndexRoute,
  AuthenticatedIntegralExtrasIndexRoute: AuthenticatedIntegralExtrasIndexRoute,
  AuthenticatedManufacturersIndexRoute: AuthenticatedManufacturersIndexRoute,
  AuthenticatedMileageAdjustmentsIndexRoute:
    AuthenticatedMileageAdjustmentsIndexRoute,
  AuthenticatedOpinionsIndexRoute: AuthenticatedOpinionsIndexRoute,
  AuthenticatedOwnersIndexRoute: AuthenticatedOwnersIndexRoute,
  AuthenticatedPriceListIndexRoute: AuthenticatedPriceListIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedProtectivesIndexRoute: AuthenticatedProtectivesIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRepositoryIndexRoute: AuthenticatedRepositoryIndexRoute,
  AuthenticatedServiceCallsIndexRoute: AuthenticatedServiceCallsIndexRoute,
  AuthenticatedServicePackagesIndexRoute:
    AuthenticatedServicePackagesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStatusesIndexRoute: AuthenticatedStatusesIndexRoute,
  AuthenticatedTechSupportIndexRoute: AuthenticatedTechSupportIndexRoute,
  AuthenticatedUpgradePackagesIndexRoute:
    AuthenticatedUpgradePackagesIndexRoute,
  AuthenticatedUsageTypesIndexRoute: AuthenticatedUsageTypesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedValuesIndexRoute: AuthenticatedValuesIndexRoute,
  AuthenticatedCatalogEditIdRoute: AuthenticatedCatalogEditIdRoute,
  AuthenticatedManufacturersEditIdRoute: AuthenticatedManufacturersEditIdRoute,
  AuthenticatedPriceListAdvertisementsIndexRoute:
    AuthenticatedPriceListAdvertisementsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
